
  /hospital:
    get:
     summary: Get all hospitals
     tags: [hospital]
     responses:
       200:
        schema:
          $ref: '#/components/schemas/hospital'
 
    post:
      summary: Create hospital
      tags: [hospital]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/hospital'
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/hospital'
 
  /hospital/{id}:
    get:
      summary: Get hospital by id
      tags: [hospital]
      parameters:
        - in: path
          name: id
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/hospital'
 
    put:
      summary: Edit hospital
      tags: [hospital]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/hospital'
      requestBody:
        content:
            application/json:
              schema:
               $ref: '#/components/schemas/hospital'
 
    delete:
      summary: Delete hospital
      tags: [hospital]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/hospital'

  /user:
    get:
     summary: Get all users
     tags: [user]
     responses:
       200:
        schema:
          $ref: '#/components/schemas/user'
 
    post:
      summary: Create user
      tags: [user]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/user'
      responses:
        201:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
 
  /user/{id}:
    get:
      summary: Get user by id
      tags: [user]
      parameters:
        - in: path
          name: id
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
 
    put:
      summary: Edit user
      tags: [user]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
      requestBody:
        content:
            application/json:
              schema:
               $ref: '#/components/schemas/user'
 
    delete:
      summary: Delete user
      tags: [user]
      parameters:
        - in: path
          name: id
      responses:
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'

  components:
    schemas:
  
      hospital:
        type: object
        properties:
      
          id:
            type: number
          city:
            type: string
          country:
            type: string
          adress:
            type: string
          phone:
            type: string
          location:
            type: string
          name:
            type: string
      user:
        type: object
        properties:
      
          id:
            type: number
          name:
            type: string
          email:
            type: string
          gender:
            type: string
          age:
            type: number
          password:
            type: string
          type:
            type: string
          bloodtype:
            type: string